import { useEffect, useState } from 'react';
import { createNotification, deleteNotification, getNotifications, markNotificationRead } from '../../api/notifications.api';

export default function NotificationsPage() {
  const [items, setItems] = useState([]); const [form, setForm] = useState({ idUtilisateur: '', titre: '', message: '', type: 'INFO' }); const [showForm, setShowForm] = useState(false); const [error, setError] = useState('');
  const load = async () => { try { setItems(await getNotifications() || []); } catch (requestError) { setError(requestError.message); } };
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); try { await createNotification(form); setForm({ idUtilisateur: '', titre: '', message: '', type: 'INFO' }); setShowForm(false); await load(); } catch (requestError) { setError(requestError.message); } };
  const read = async (id) => { try { await markNotificationRead(id); await load(); } catch (requestError) { setError(requestError.message); } };
  const remove = async (id) => { try { await deleteNotification(id); await load(); } catch (requestError) { setError(requestError.message); } };
  return <section className="page-shell"><div className="page-header"><div><p className="eyebrow">Centre de notifications</p><h1>Notifications</h1><p className="page-lead">Créez, lisez et archivez les notifications utilisateurs.</p></div><button className="primary-button" onClick={() => setShowForm(!showForm)}>{showForm ? 'Fermer' : '+ Nouvelle notification'}</button></div>{error && <div className="error-box">{error}</div>}{showForm && <form className="card-panel entity-form" onSubmit={submit}><h2>Nouvelle notification</h2><div className="form-grid"><label className="field">ID utilisateur<input required type="number" value={form.idUtilisateur} onChange={(event) => setForm({ ...form, idUtilisateur: event.target.value })} /></label><label className="field">Titre<input required value={form.titre} onChange={(event) => setForm({ ...form, titre: event.target.value })} /></label><label className="field">Type<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option value="INFO">Information</option><option value="ALERTE">Alerte</option><option value="RAPPEL">Rappel</option></select></label></div><label className="field">Message<textarea required rows="3" value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} /></label><button className="primary-button">Envoyer</button></form>}<div className="card-panel entity-panel"><div className="table-wrap"><table><thead><tr><th>Titre</th><th>Message</th><th>Type</th><th>État</th><th>Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.titre}</td><td>{item.message}</td><td>{item.type}</td><td><span className={`status-pill ${item.lu ? 'status-success' : 'status-warning'}`}>{item.lu ? 'Lue' : 'Non lue'}</span></td><td>{!item.lu && <button className="table-action" onClick={() => read(item.id)}>Marquer lue</button>}<button className="table-action danger-action" onClick={() => remove(item.id)}>Supprimer</button></td></tr>)}{!items.length && <tr><td colSpan="5" className="state-message">Aucune notification.</td></tr>}</tbody></table></div></div></section>;
}