import { useEffect, useState } from 'react';
import { getAbsencesEleve, justifierAbsence, uploaderDocumentAbsence } from '../../api/absences.api';
import { getEleves } from '../../api/eleves.api';

export default function AbsencesPage() {
  const [students, setStudents] = useState([]); const [studentId, setStudentId] = useState(''); const [absences, setAbsences] = useState([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { getEleves().then(setStudents).catch((requestError) => setError(requestError.message)); }, []);
  const load = async (id) => { setStudentId(id); if (!id) return setAbsences([]); setLoading(true); setError(''); try { setAbsences(await getAbsencesEleve(id) || []); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } };
  const justify = async (absence) => { const motif = window.prompt('Motif de justification'); if (motif === null) return; try { await justifierAbsence(absence.id, { motif }); setMessage('Absence justifiée.'); await load(studentId); } catch (requestError) { setError(requestError.message); } };
  const upload = async (absence, event) => { const file = event.target.files[0]; if (!file) return; try { await uploaderDocumentAbsence(absence.id, file); setMessage('Document envoyé.'); await load(studentId); } catch (requestError) { setError(requestError.message); } };
  const justified = absences.filter((absence) => absence.justifiee).length;
  return <section className="page-shell"><div className="page-header"><div><p className="eyebrow">Suivi scolaire</p><h1>Absences</h1><p className="page-lead">Justifiez les absences et associez les documents nécessaires.</p></div></div><div className="card-panel absence-filters"><label className="field"><span>Choisir un élève</span><select value={studentId} onChange={(event) => load(event.target.value)}><option value="">Sélectionner un élève...</option>{students.map((student) => <option key={student.id} value={student.id}>{student.prenom} {student.nom}</option>)}</select></label></div>{message && <div className="feedback-box">{message}</div>}{error && <div className="error-box">{error}</div>}{studentId && <div className="stats-grid absence-stats"><article className="stat-card"><span>Total absences</span><strong>{absences.length}</strong></article><article className="stat-card"><span>Justifiées</span><strong>{justified}</strong></article><article className="stat-card"><span>À traiter</span><strong>{absences.length - justified}</strong></article></div>}{studentId && <div className="card-panel entity-panel">{loading ? <p className="state-message">Chargement...</p> : <div className="table-wrap"><table><thead><tr><th>Date</th><th>Matière</th><th>Statut</th><th>Motif</th><th>Documents</th><th>Actions</th></tr></thead><tbody>{absences.map((absence) => <tr key={absence.id}><td>{absence.dateAbsence}</td><td>{absence.nomMatiere || '—'}</td><td><span className={`status-pill ${absence.justifiee ? 'status-success' : 'status-warning'}`}>{absence.justifiee ? 'Justifiée' : 'À justifier'}</span></td><td>{absence.motif || 'Aucun motif'}</td><td>{absence.documentName || 'Aucun document'}</td><td><button className="table-action" onClick={() => justify(absence)}>Justifier</button><label className="table-action upload-label">Document<input hidden type="file" accept="application/pdf,image/*" onChange={(event) => upload(absence, event)} /></label></td></tr>)}{!absences.length && <tr><td colSpan="6" className="state-message">Aucune absence enregistrée.</td></tr>}</tbody></table></div>}</div>}</section>;
}
