import { useState } from 'react';
import { getAbsenceStats, getAbsencesClasse, getAbsencesEnseignant } from '../../api/absences.api';

export default function AbsenceAudiencePage({ mode = 'classe' }) {
  const [id, setId] = useState(''); const [items, setItems] = useState([]); const [stats, setStats] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const load = async (event) => { const value = event.target.value; setId(value); setItems([]); setStats(null); if (!value) return; setLoading(true); setError(''); try { if (mode === 'stats') setStats(await getAbsenceStats(value)); else setItems(await (mode === 'enseignant' ? getAbsencesEnseignant(value) : getAbsencesClasse(value)) || []); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } };
  const title = mode === 'enseignant' ? 'Absences par enseignant' : mode === 'stats' ? 'Statistiques des absences' : 'Absences par classe';
  return <section className="page-shell"><div className="page-header"><div><p className="eyebrow">Suivi scolaire</p><h1>{title}</h1><p className="page-lead">Analysez les absences selon le périmètre choisi.</p></div></div><div className="card-panel mb-4"><label className="field">{mode === 'enseignant' ? 'ID enseignant' : 'ID classe'}<input type="number" value={id} onChange={load} placeholder="Saisir un identifiant" /></label></div>{error && <div className="error-box">{error}</div>}{loading && <p className="state-message">Chargement...</p>}{stats && <div className="stats-grid mb-4"><article className="stat-card"><span>Total</span><strong>{stats.total}</strong></article><article className="stat-card"><span>Justifiées</span><strong>{stats.justifiees}</strong></article><article className="stat-card"><span>Taux d’absence</span><strong>{stats.tauxAbsence}%</strong></article></div>}{!stats && id && !loading && <div className="card-panel entity-panel"><div className="table-wrap"><table><thead><tr><th>Date</th><th>Élève</th><th>Matière</th><th>Classe</th><th>Statut</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.dateAbsence}</td><td>{item.prenomEleve} {item.nomEleve}</td><td>{item.nomMatiere || '—'}</td><td>{item.nomClasse || '—'}</td><td>{item.justifiee ? 'Justifiée' : 'À traiter'}</td></tr>)}{!items.length && <tr><td colSpan="5" className="state-message">Aucune absence.</td></tr>}</tbody></table></div></div>}</section>;
+}
