import { useMemo, useState } from 'react';
import { useEntityList } from '../../hooks/useEntityList';

export default function ResourcePage({ eyebrow = 'Administration', title, description, loader, columns, emptyLabel = 'Aucun élément trouvé.', createAction, updateAction, deleteAction, formFields = [], rowActions = [] }) {
  const { items, loading, error, reload } = useEntityList(loader);
  const [query, setQuery] = useState('');
  const [form, setForm] = useState(() => Object.fromEntries(formFields.map((field) => [field.name, ''])));
  const [showForm, setShowForm] = useState(false);
  const [editingItem, setEditingItem] = useState(null);
  const [feedback, setFeedback] = useState('');
  const [saving, setSaving] = useState(false);
  const filtered = useMemo(() => items.filter((item) => JSON.stringify(item).toLowerCase().includes(query.toLowerCase())), [items, query]);
  const openCreate = () => { setEditingItem(null); setForm(Object.fromEntries(formFields.map((field) => [field.name, '']))); setShowForm(true); };
  const openEdit = (item) => { setEditingItem(item); setForm(Object.fromEntries(formFields.map((field) => [field.name, item[field.name] ?? '']))); setShowForm(true); };
  const submit = async (event) => { event.preventDefault(); setSaving(true); setFeedback(''); try { const id = editingItem?.id || editingItem?.idAnnee || editingItem?.idPaiement || editingItem?.idAnnonce; await (editingItem && updateAction ? updateAction(id, form) : createAction(form)); setForm(Object.fromEntries(formFields.map((field) => [field.name, '']))); setEditingItem(null); setShowForm(false); setFeedback('Enregistrement effectué.'); await reload(); } catch (requestError) { setFeedback(requestError.message); } finally { setSaving(false); } };
  const remove = async (item) => { if (!window.confirm('Confirmer la suppression de cet élément ?')) return; try { await deleteAction(item.id || item.idAnnee || item.idPaiement || item.idAnnonce); setFeedback('Élément supprimé.'); await reload(); } catch (requestError) { setFeedback(requestError.message); } };
  return <section className="page-shell"><div className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="page-lead">{description}</p></div>{(createAction || updateAction) && <button className="primary-button" onClick={showForm ? () => setShowForm(false) : openCreate}>{showForm ? 'Fermer' : '+ Ajouter'}</button>}</div>{feedback && <div className="feedback-box">{feedback}</div>}{showForm && <form className="card-panel entity-form" onSubmit={submit}><h2>{editingItem ? 'Modifier l’élément' : 'Nouvel élément'}</h2><div className="form-grid">{formFields.map((field) => <label className="field" key={field.name}>{field.label}<input required={field.required} type={field.type || 'text'} name={field.name} value={form[field.name]} onChange={(event) => setForm({ ...form, [field.name]: event.target.value })} /></label>)}</div><button className="primary-button" disabled={saving}>{saving ? 'Enregistrement...' : 'Enregistrer'}</button></form>}<div className="card-panel entity-panel"><div className="table-toolbar"><strong>{items.length} élément{items.length > 1 ? 's' : ''}</strong><input className="search-input" placeholder="Rechercher..." value={query} onChange={(event) => setQuery(event.target.value)} /></div>{loading ? <p className="state-message">Chargement des données...</p> : error ? <p className="state-message error-text">{error}</p> : <div className="table-wrap"><table><thead><tr>{columns.map((column) => <th key={column.label}>{column.label}</th>)}{(updateAction || deleteAction || rowActions.length) && <th>Actions</th>}</tr></thead><tbody>{filtered.map((item, index) => <tr key={item.id || item.idAnnee || item.idPaiement || item.idAnnonce || index}>{columns.map((column) => <td key={column.label}>{column.render ? column.render(item) : item[column.key] ?? '—'}</td>)}{(updateAction || deleteAction || rowActions.length) && <td>{rowActions.map((action) => <button className={`table-action ${action.danger ? 'danger-action' : ''}`} key={action.label} onClick={() => action.onClick(item, reload, setFeedback)}>{action.label}</button>)}{updateAction && <button className="table-action" onClick={() => openEdit(item)}>Modifier</button>}{deleteAction && <button className="table-action danger-action" onClick={() => remove(item)}>Supprimer</button>}</td>}</tr>)}{!filtered.length && <tr><td colSpan={columns.length + (updateAction || deleteAction || rowActions.length ? 1 : 0)} className="state-message">{emptyLabel}</td></tr>}</tbody></table></div>}</div></section>;
}