import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { getEleves } from '../../api/eleves.api';
import { getEnseignants } from '../../api/enseignants.api';
import { getClasses } from '../../api/classes.api';
import { getInscriptions } from '../../api/inscriptions.api';
import { getNotifications } from '../../api/notifications.api';

const modules = [
  { label: 'Élèves', detail: 'Dossiers, contacts et inscriptions', to: '/gestion-scolaire', tone: 'bg-blue-50 text-blue-700' },
  { label: 'Équipe pédagogique', detail: 'Enseignants et affectations', to: '/admin/enseignants', tone: 'bg-violet-50 text-violet-700' },
  { label: 'Scolarité', detail: 'Classes, formations et inscriptions', to: '/admin/classes', tone: 'bg-emerald-50 text-emerald-700' },
  { label: 'Finance', detail: 'Paiements et échéances', to: '/comptabilite', tone: 'bg-amber-50 text-amber-700' },
  { label: 'Communication', detail: 'Annonces et notifications', to: '/communication', tone: 'bg-cyan-50 text-cyan-700' },
  { label: 'Sécurité', detail: 'Utilisateurs et permissions', to: '/admin/utilisateurs', tone: 'bg-rose-50 text-rose-700' },
];

export default function AdminDashboardPage() {
  const [metrics, setMetrics] = useState({ students: 0, teachers: 0, classes: 0, pending: 0 });
  const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.allSettled([getEleves(), getEnseignants(), getClasses(), getInscriptions(), getNotifications()]).then(([students, teachers, classes, inscriptions]) => setMetrics({ students: students.value?.length || 0, teachers: teachers.value?.length || 0, classes: classes.value?.length || 0, pending: inscriptions.value?.filter((item) => item.statut === 'EN_ATTENTE').length || 0 })).finally(() => setLoading(false)); }, []);
  const cards = [{ label: 'Élèves inscrits', value: metrics.students, detail: 'Dossiers actifs', tone: 'bg-blue-50 text-blue-700' }, { label: 'Enseignants', value: metrics.teachers, detail: 'Équipe pédagogique', tone: 'bg-violet-50 text-violet-700' }, { label: 'Classes', value: metrics.classes, detail: 'Groupes configurés', tone: 'bg-emerald-50 text-emerald-700' }, { label: 'À valider', value: metrics.pending, detail: 'Inscriptions en attente', tone: 'bg-amber-50 text-amber-700' }];
  return <section className="page-shell"><div className="page-header"><div><p className="eyebrow">Administration</p><h1 className="text-3xl font-extrabold tracking-tight text-slate-800">Centre de pilotage</h1><p className="page-lead">Une vue claire sur les opérations de votre établissement.</p></div><Link className="primary-button" to="/admin/utilisateurs">Gérer les utilisateurs →</Link></div><div className="stats-grid mb-6 lg:grid-cols-4">{cards.map((card) => <article className="stat-card" key={card.label}><div className={`mb-5 grid size-10 place-items-center rounded-xl ${card.tone}`}>▦</div><span className="text-sm text-slate-500">{card.label}</span><strong className="mt-1 block text-3xl font-extrabold text-slate-800">{loading ? '—' : card.value}</strong><small className="mt-2 block text-xs text-slate-400">{card.detail}</small></article>)}</div><div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><section className="card-panel"><div className="mb-5 flex items-start justify-between"><div><p className="eyebrow">Modules</p><h2 className="mt-1 text-lg font-bold text-slate-800">Accès d’administration</h2></div><span className="rounded-full bg-green-50 px-3 py-1 text-xs font-bold text-green-700">Système opérationnel</span></div><div className="grid gap-3 sm:grid-cols-2">{modules.map((module) => <Link className="group flex items-center gap-3 rounded-xl border border-slate-200 p-4 no-underline transition hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-sm" key={module.to} to={module.to}><span className={`grid size-10 shrink-0 place-items-center rounded-xl text-lg ${module.tone}`}>↗</span><span className="min-w-0"><strong className="block text-sm font-bold text-slate-800">{module.label}</strong><small className="mt-1 block text-xs text-slate-400">{module.detail}</small></span><span className="ml-auto text-slate-300 transition group-hover:text-blue-600">→</span></Link>)}</div></section><aside className="card-panel bg-slate-900 text-white"><p className="text-xs font-bold uppercase tracking-wider text-blue-300">Contrôle quotidien</p><h2 className="mt-3 text-xl font-bold">Tout est centralisé.</h2><p className="mt-3 text-sm leading-6 text-slate-300">Les comptes, les données scolaires, la communication et la comptabilité sont accessibles depuis cet espace sécurisé.</p><div className="mt-8 grid gap-3 border-t border-white/10 pt-5 text-sm"><div className="flex justify-between"><span className="text-slate-400">Année active</span><strong>2025 - 2026</strong></div><div className="flex justify-between"><span className="text-slate-400">Sécurité</span><strong className="text-emerald-300">Protégée</strong></div></div></aside></div></section>;
}